export default {
    SET_USER: 'SET_USER',
    SET_PATIENT: 'SET_PATIENT',
    SET_PATIENT_CONTEXT: 'SET_PATIENT_CONTEXT',
    SET_SELECTED_MODULE: 'SET_SELECTED_MODULE',
    SET_SELECTED_MODULE_TITLE: 'SET_SELECTED_MODULE_TITLE',
    SET_CLIENTS: 'SET_CLIENTS',
    SET_TOKEN: 'SET_TOKEN',
    SET_SHOW_DRAWER: 'SET_SHOW_DRAWER',
    SET_SHOW_NOTIFICATIONS: 'SET_SHOW_NOTIFICATIONS',
    SET_SHOW_DASHBOARD: 'SET_SHOW_DASHBOARD',
    LOGOUT: 'LOGOUT',
    SET_NOTIFICATIONS: 'SET_NOTIFICATIONS'
}