export default {
    SET_USER: 'SET_USER',
    SET_PATIENT: 'SET_PATIENT',
    SET_PATIENT_CONTEXT: 'SET_PATIENT_CONTEXT',
    SET_SELECTED_MODULE: 'SET_SELECTED_MODULE',
    SET_SELECTED_MODULE_TITLE: 'SET_SELECTED_MODULE_TITLE',
    SET_CLIENTS: 'SET_CLIENTS',
    SET_TOKEN: 'SET_TOKEN',
    LOGOUT: 'LOGOUT'
}